name: 'PlanetScale: Create Database Branch'
description: 'Creates a branch for a PlanetScale database.'
branding:
  color: 'orange'
  icon: 'database'
author: 'PlanetScale'
inputs:
  organization:
    description: 'Name of the organization.'
    required: true
  database: 
    description: 'Name of the database.'
    required: true
  branch:
    description: 'Name of the branch. If left blank, will use same name as the current git branch.'
    required: false
  from:
    description: 'The production branch to create the new branch from.'
    required: false
  restore:
    description: 'The ID of the backup you wish to restore into the new branch.'
    required: false
  region:
    description: 'The region where the new branch should be created. Defaults to the region of the `from` branch.'
    required: false
  wait:
    description: 'If set to "true", the action will wait until the branch is finished initializing before exiting.'
    required: false
  check_exists:
    description: "If set to \"true\", the action won't create the branch if it already exists."
    required: false
  seed_data:
    description: "Set to \"true\", to enable seed data from the latest backup using Data Branching™"
    required: false
  version: 
    description: 'Version of pscale to install. i.e. v0.106.0. Defaults to latest version.'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
    - name: Setup pscale
      uses: planetscale/setup-pscale-action@main
      with:
        version: ${{ inputs.version }}
    - name: Create branch and connection
      env:
        ORGANIZATION: ${{ inputs.organization }}
        DATABASE: ${{ inputs.database }}
        BRANCH: ${{ inputs.branch }}
        FROM: ${{ inputs.from }}
        WAIT: ${{ inputs.wait }}
        REGION: ${{ inputs.region }}
        RESTORE: ${{ inputs.restore }}
      shell: bash
      run:
        ls dist
        cat dist/index.js
        node dist/index.js
